//! Standard gRPC Health Checking Protocol (`grpc.health.v1.Health`).
//!
//! This closes the tracked gap "no health-checking endpoint": readiness was
//! internal state an orchestrator could only infer from a TCP dial. Serving
//! the STANDARD protocol (gRPC proposal A14) means stock clients — Kubernetes
//! `grpc:` readiness probes, Envoy's gRPC health checker, grpcurl — observe
//! readiness with no bespoke code, on the same port as classify. The schema
//! is the frozen standard and lives in `proto/health.proto`, generated by the
//! same `tonic-prost-build` pipeline as classify.proto, so no `tonic-health`
//! dependency is pulled for what is two RPCs over two messages.
//!
//! Semantics:
//!   - `Check("")` is the WHOLE server; `Check("classify.Classify")` is the
//!     classify service. Both map the construction-time [`Readiness`]: a
//!     [`ClassifyServer`](crate::grpc::classify::ClassifyServer) only exists
//!     after the model is loaded and warmed (a ModelCar that fails load or
//!     warmup never reaches the bind), so a bound server reports SERVING. A
//!     service name this server does not know is an explicit NOT_FOUND.
//!   - `Watch` streams the current status first, then stays open. Readiness
//!     is fixed at bind time, so there is no later transition to report; if
//!     readiness ever becomes dynamic (e.g. graceful drain), the status
//!     source in [`HealthService`] is the single place to change.

use crate::runtime::Readiness;
use std::io;
use std::pin::Pin;
use std::time::Duration;
use tokio_stream::StreamExt;
use tonic::transport::Endpoint;

/// Generated protobuf messages and tonic service/client code for
/// `grpc.health.v1` (from `proto/health.proto`, produced by `build.rs`).
///
/// The proto package is `grpc.health.v1`, so the generated items nest under
/// matching modules; the re-exports below keep the commonly used names flat.
pub mod generated {
    pub mod grpc {
        pub mod health {
            pub mod v1 {
                tonic::include_proto!("grpc.health.v1");
            }
        }
    }
}

pub use generated::grpc::health::v1::health_check_response::ServingStatus;
pub use generated::grpc::health::v1::{
    health_client, health_server, HealthCheckRequest, HealthCheckResponse,
};

/// The standard health service, serving the protocol's `Check` and `Watch`.
pub struct HealthService {
    /// True when the runtime this service fronts is ready to serve traffic.
    serving: bool,
    /// Fully-qualified gRPC service names this server serves (e.g.
    /// [`crate::grpc::classify::SERVICE_NAME`]). The empty service name — the
    /// WHOLE server, per the protocol — is always known and never listed.
    services: Vec<String>,
}

impl HealthService {
    /// A health service reporting `readiness` for the whole server and for
    /// each fully-qualified name in `services`.
    pub fn new(readiness: Readiness, services: &[&str]) -> Self {
        HealthService {
            serving: readiness.ready(),
            services: services.iter().map(|s| (*s).to_string()).collect(),
        }
    }

    /// The serving status for `service`, or `None` when this server does not
    /// know that service name at all.
    fn status(&self, service: &str) -> Option<ServingStatus> {
        if service.is_empty() || self.services.iter().any(|s| s == service) {
            Some(if self.serving {
                ServingStatus::Serving
            } else {
                ServingStatus::NotServing
            })
        } else {
            None
        }
    }
}

#[tonic::async_trait]
impl health_server::Health for HealthService {
    type WatchStream = Pin<
        Box<dyn tokio_stream::Stream<Item = Result<HealthCheckResponse, tonic::Status>> + Send>,
    >;

    async fn check(
        &self,
        request: tonic::Request<HealthCheckRequest>,
    ) -> Result<tonic::Response<HealthCheckResponse>, tonic::Status> {
        let service = request.into_inner().service;
        match self.status(&service) {
            Some(status) => Ok(tonic::Response::new(HealthCheckResponse {
                status: status as i32,
            })),
            None => Err(tonic::Status::not_found(format!(
                "unknown service: {service}"
            ))),
        }
    }

    async fn watch(
        &self,
        request: tonic::Request<HealthCheckRequest>,
    ) -> Result<tonic::Response<Self::WatchStream>, tonic::Status> {
        // Watch never fails for an unknown service: per the protocol it
        // reports SERVICE_UNKNOWN (NOT_FOUND is a Check-only error).
        let status = self
            .status(&request.into_inner().service)
            .unwrap_or(ServingStatus::ServiceUnknown);
        // The current status first, then keep the stream open for the rest of
        // the RPC: readiness is fixed at bind time, so there is no later
        // transition to stream. The stream ends when the client cancels.
        let stream = tokio_stream::once(Ok(HealthCheckResponse {
            status: status as i32,
        }))
        .chain(tokio_stream::pending());
        Ok(tonic::Response::new(Box::pin(stream)))
    }
}

/// Blocking health client over a persistent HTTP/2 channel.
///
/// Mirrors [`crate::grpc::classify::ClassifyClient`]: one channel, owned by a
/// private Tokio runtime, so synchronous callers (tests, probe tooling) can
/// speak the standard protocol without touching an async runtime.
pub struct HealthClient {
    runtime: tokio::runtime::Runtime,
    channel: tonic::transport::Channel,
}

impl HealthClient {
    /// Connect to a server's standard health service at `addr`.
    pub fn connect(addr: impl AsRef<str>) -> io::Result<HealthClient> {
        let addr_str = addr.as_ref();
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .map_err(io::Error::other)?;

        let endpoint = Endpoint::from_shared(format!("http://{addr_str}"))
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidInput, e))?
            .connect_timeout(Duration::from_secs(5))
            .tcp_nodelay(true);

        let channel = runtime
            .block_on(endpoint.connect())
            .map_err(io::Error::other)?;

        Ok(HealthClient { runtime, channel })
    }

    /// The serving status for `service` ("" for the whole server).
    ///
    /// An unknown service name surfaces the protocol's NOT_FOUND error.
    pub fn check(&mut self, service: &str) -> Result<ServingStatus, tonic::Status> {
        let mut client = health_client::HealthClient::new(self.channel.clone());
        let response = self
            .runtime
            .block_on(client.check(HealthCheckRequest {
                service: service.to_string(),
            }))?
            .into_inner();
        ServingStatus::try_from(response.status)
            .map_err(|_| tonic::Status::internal("invalid serving status on the wire"))
    }

    /// The first status `Watch` streams for `service`.
    ///
    /// The protocol streams the current status first, so this observes exactly
    /// what a long-lived watcher would see on connect, while proving the
    /// streaming RPC actually carries a status.
    pub fn watch(&mut self, service: &str) -> Result<ServingStatus, tonic::Status> {
        let mut client = health_client::HealthClient::new(self.channel.clone());
        let mut stream = self
            .runtime
            .block_on(client.watch(HealthCheckRequest {
                service: service.to_string(),
            }))?
            .into_inner();
        let first = self
            .runtime
            .block_on(stream.next())
            .ok_or_else(|| tonic::Status::unavailable("health watch ended without a status"))?;
        let response = first?;
        ServingStatus::try_from(response.status)
            .map_err(|_| tonic::Status::internal("invalid serving status on the wire"))
    }
}

#[cfg(test)]
mod tests {
    use super::{HealthService, ServingStatus};
    use crate::runtime::Readiness;

    /// A not-ready runtime must report NOT_SERVING, never SERVING: the health
    /// endpoint is only useful if it can fail. No public bind path constructs
    /// a NotReady server today (bind happens only after warmup succeeds), so
    /// the readiness mapping is pinned here at the unit level.
    #[test]
    fn not_ready_runtime_reports_not_serving() {
        let health = HealthService::new(Readiness::NotReady, &["classify.Classify"]);
        assert_eq!(health.status(""), Some(ServingStatus::NotServing));
        assert_eq!(
            health.status("classify.Classify"),
            Some(ServingStatus::NotServing)
        );
    }

    /// A service name the server does not serve is unknown: Check must be able
    /// to answer NOT_FOUND (and Watch SERVICE_UNKNOWN) rather than inventing a
    /// status for a service that is not there.
    #[test]
    fn unknown_service_name_has_no_status() {
        let health = HealthService::new(Readiness::Ready, &["classify.Classify"]);
        assert_eq!(health.status("no.such.Service"), None);
    }
}
