#!/usr/bin/env python3
"""Generate matched taxonomy + Praxis config pairs for the route-count dimension.

"How many routes are we routing between" is a GATEWAY question, so it has to vary
the number of clusters in the Praxis route table -- which in turn requires a
taxonomy with that many labels. Round 1 only varied anchor count within a fixed
4-label taxonomy, which measures ranking cost, not route-table size. Both matter
and they are different axes.

Emits, for each N in ROUTE_COUNTS:
  taxonomy-<N>.json   N labels, 12 anchors each
  praxis-<N>.yaml     N clusters, one per label, plus a `general` fail-open
"""
import json, os, sys

ROUTE_COUNTS = [2, 4, 8, 16, 32]
OUT = os.path.dirname(os.path.abspath(__file__))

base = json.load(open(os.path.join(OUT, "..", "..", "classifiers", "complexity.json")))
src_anchors = [a for v in base["anchors"].values() for a in v]

def taxonomy(n):
    labels = [f"TIER{i:02d}" for i in range(n)]
    anchors = {}
    for i, lab in enumerate(labels):
        # Deterministic, distinct, but drawn from the real anchor corpus so the
        # embeddings stay in a realistic region of the space.
        anchors[lab] = [f"{src_anchors[(i * 12 + j) % len(src_anchors)]} [{lab} sense {j}]"
                        for j in range(12)]
    d = dict(base)
    d.update(classifier_id=f"routes{n}", taxonomy_revision=f"routes-{n}-v1",
             labels=labels, anchors=anchors)
    return d, labels

def praxis_config(n, labels):
    routes = "\n".join(
        f"          - {{label: {l}, cluster: tier{i:02d}}}" for i, l in enumerate(labels))
    clusters = "\n".join(
        f"          - name: tier{i:02d}\n"
        f"            endpoints: [\"vcr-small.cnuland-dev.svc.cluster.local:8000\"]"
        for i in range(n))
    return f"""# Generated by round2/gen_routes.py -- {n}-cluster route table.
#
# Every tier points at the SAME backend on purpose. The variable under test is
# the size of the route table the gateway must evaluate, so the destination must
# be held constant; otherwise a routing change would also change the backend and
# the two effects would be inseparable.
admin:
  address: "0.0.0.0:9901"
  verbose: true
insecure_options:
  allow_public_admin: true
listeners:
  - name: http
    address: "0.0.0.0:8080"
    filter_chains: [ai-routing]
  - name: baseline
    address: "0.0.0.0:8081"
    filter_chains: [baseline]
filter_chains:
  - name: ai-routing
    filters:
      - filter: request_id
      - filter: access_log
      - filter: llm_d_sc
        endpoint: "llm-d-sc.cnuland-dev.svc.cluster.local:50051"
        default_cluster: general
        timeout_ms: 1000
        routes:
{routes}
      - filter: load_balancer
        clusters:
{clusters}
          - name: general
            endpoints: ["vcr-small.cnuland-dev.svc.cluster.local:8000"]
  - name: baseline
    filters:
      - filter: request_id
      - filter: access_log
      - filter: router
        routes:
          - path_prefix: "/"
            cluster: general
      - filter: load_balancer
        clusters:
          - name: general
            endpoints: ["vcr-small.cnuland-dev.svc.cluster.local:8000"]
"""

if __name__ == "__main__":
    for n in ROUTE_COUNTS:
        tax, labels = taxonomy(n)
        open(os.path.join(OUT, f"taxonomy-{n}.json"), "w").write(json.dumps(tax))
        open(os.path.join(OUT, f"praxis-{n}.yaml"), "w").write(praxis_config(n, labels))
        print(f"routes={n:>3}: taxonomy-{n}.json ({n} labels x 12 anchors), praxis-{n}.yaml ({n} clusters)")
