#!/usr/bin/env python3
"""Assemble the corrected knee section from r3b results.

The previous knee claims were withdrawn for two reasons: a warmup carry-in that
inflated every offered rate by concurrency/window, and a Zipf workload whose
hit ratio drifted with the rate, so the sweep never held one variable. Both are
fixed; this reads only the corrected r3b arms.
"""
import glob, json, statistics, sys, os
from collections import defaultdict

SRC = sys.argv[1] if len(sys.argv) > 1 else "../results"
g = defaultdict(list)
for p in glob.glob(os.path.join(SRC, "json", "r3b-*.json")):
    try:
        d = json.load(open(p)); g[d["label"].rsplit("-rep", 1)[0]].append(d)
    except Exception:
        pass
if not g:
    print("no r3b results"); sys.exit(0)

med = statistics.median
STACKS = [("praxis", "Praxis + llm-d-sc"), ("llmd", "llm-d IPP + llm-d-sc"),
          ("vsr", "vLLM SR adapter + llm-d-sc")]
REGIMES = [("miss", "100% novel (classifier compute capacity)"),
           ("mix80", "80% warm / 20% novel (controlled blend)"),
           ("hit", "100% cached (service + transport capacity)")]

out = ["## Corrected knees — open-loop, hit ratio pinned by construction\n",
       "Arrival rate is generated by a central scheduler at a true Poisson process, "
       "independent of response latency. The hit ratio is fixed by the regime rather "
       "than drifting with the rate, and every `miss` arm is salted so its prompts "
       "cannot be served from a cache warmed by an earlier run.\n"]

summary = []
for sk, sname in STACKS:
    for rk, rname in REGIMES:
        rows = []
        for k in sorted(g):
            if not k.startswith(f"r3b-{sk}-{rk}-rate"): continue
            rate = int(k.split("rate")[1]); reps = g[k]
            L = lambda f: med([r["latency"][f] for r in reps])
            rows.append(dict(rate=rate,
                             comp=med([r.get("completed_rps", r["throughput_rps"]) for r in reps]),
                             off=med([r.get("offer_attainment", 1.0) for r in reps]),
                             p50=L("p50_ms"), p90=L("p90_ms"), p99=L("p99_ms"),
                             mean=L("mean_ms"), sd=L("stddev_ms"),
                             rej=med([r.get("rejected_rps", 0.0) for r in reps]),
                             ok=all(r.get("premises_passed", True) for r in reps),
                             n=len(reps)))
        if not rows: continue
        rows.sort(key=lambda x: x["rate"])
        out.append(f"\n### {sname} — {rname}\n")
        out.append("| offered rps | completed rps | offer attain | p50 ms | p90 ms | p99 ms | "
                   "mean ms | stddev | rejected/s | reps | premises |")
        out.append("|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|:--|")
        for r in rows:
            out.append(f"| {r['rate']:,} | {r['comp']:,.1f} | {r['off']:.3f} | {r['p50']:.2f} | "
                       f"{r['p90']:.2f} | {r['p99']:.2f} | {r['mean']:.2f} | {r['sd']:.2f} | "
                       f"{r['rej']:,.1f} | {r['n']} | {'ok' if r['ok'] else '**FAILED**'} |")
        # knees
        lat = None
        for i in range(1, len(rows)):
            if rows[i-1]["p90"] > 0 and rows[i]["p90"] / rows[i-1]["p90"] >= 5.0:
                lat = (rows[i-1]["rate"], rows[i]["rate"], rows[i-1]["p90"], rows[i]["p90"]); break
        sat = next((r["rate"] for r in rows if r["comp"] < r["rate"] * 0.95), None)
        if lat:
            out.append(f"\n**Latency knee: {lat[0]:,} → {lat[1]:,} rps** — p90 {lat[2]:.2f} → "
                       f"{lat[3]:.2f} ms (**{lat[3]/lat[2]:.0f}×**).")
        else:
            out.append(f"\n**No latency knee** through {rows[-1]['rate']:,} rps — p90 stays "
                       f"{rows[0]['p90']:.2f} → {rows[-1]['p90']:.2f} ms.")
        out.append(f"Saturation: {'completion falls behind offer at %s rps' % f'{sat:,}' if sat else 'not reached'}.\n")
        summary.append((sname, rname, lat, rows[-1]["rate"]))

out.append("\n### Knee summary — position tracks miss fraction\n")
out.append("| stack | regime | latency knee |")
out.append("|---|---|---|")
for sname, rname, lat, maxr in summary:
    out.append(f"| {sname} | {rname.split('(')[0].strip()} | "
               + (f"{lat[0]:,} → {lat[1]:,} rps ({lat[3]/lat[2]:.0f}×)" if lat
                  else f"none through {maxr:,} rps") + " |")
out.append("\nThe knee moves monotonically with the fraction of novel prompts, which is "
           "what queueing theory predicts when the model forward is the constrained "
           "resource. The earlier, withdrawn sweep reported the *same* knee for every "
           "regime — the signature of regimes that were not actually different.\n")
print("\n".join(out))
