//! I-025: the Rust Candle embedding must agree with a pinned Python reference.
//!
//! Everything downstream (anchors, ranking, cache keys, published accuracy)
//! assumes the Rust forward reproduces what the model produces under the
//! reference implementation. If pooling, truncation, or tokenisation drifts, the
//! service still returns confident, well-formed, WRONG rankings, and no other
//! test would notice because every other test compares Rust against Rust.
//!
//! The fixture is generated by `transformers` AutoModel with explicit mean
//! pooling (see tests/fixtures/python-reference-embeddings.json) and committed,
//! so this test is offline and deterministic.
//!
//! Requires fetched weights: `./hack/fetch-model --classifier complexity` and
//! `--classifier sensitivity`. Run with `cargo test --test embedding_parity -- --ignored`.

use llm_d_sc::embedding::Embedder;

/// Cosine similarity between the Rust and Python vectors.
fn cosine(a: &[f32], b: &[f32]) -> f64 {
    let dot: f64 = a.iter().zip(b).map(|(x, y)| f64::from(*x) * f64::from(*y)).sum();
    let na: f64 = a.iter().map(|x| f64::from(*x).powi(2)).sum::<f64>().sqrt();
    let nb: f64 = b.iter().map(|x| f64::from(*x).powi(2)).sum::<f64>().sqrt();
    dot / (na * nb)
}

/// L2-normalize to unit length.
///
/// The Rust `Embedder` applies the `Normalize` module the ModelCar declares in
/// `modules.json`; the reference fixture stores the RAW mean-pooled vector. So
/// the two agree in direction but not magnitude, and a raw component comparison
/// would fail on a scale factor rather than on a defect. Normalising both sides
/// compares what every consumer actually uses, since ranking is cosine and
/// therefore scale-invariant.
fn unit(v: &[f32]) -> Vec<f32> {
    let n: f64 = v.iter().map(|x| f64::from(*x).powi(2)).sum::<f64>().sqrt();
    if n == 0.0 {
        return v.to_vec();
    }
    v.iter().map(|x| (f64::from(*x) / n) as f32).collect()
}

/// Largest absolute per-component difference.
fn max_abs_diff(a: &[f32], b: &[f32]) -> f64 {
    a.iter()
        .zip(b)
        .map(|(x, y)| (f64::from(*x) - f64::from(*y)).abs())
        .fold(0.0, f64::max)
}

#[test]
#[ignore]
fn i025_rust_embedding_agrees_with_pinned_python_reference() {
    let raw = std::fs::read_to_string(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/python-reference-embeddings.json"),
    )
    .expect("reference fixture must be committed");
    let fixture: serde_json::Value = serde_json::from_str(&raw).unwrap();
    let texts: Vec<String> = fixture["texts"]
        .as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();

    // Also assert the Rust output is unit-norm, since the comparison below
    // normalises both sides and would otherwise hide a missing Normalize module.
    // Cosine tolerance: f32 accumulation order differs between Candle and torch,
    // so bit-identical output is not achievable. Anything below this indicates a
    // real semantic divergence (wrong pooling, wrong truncation, wrong tokens),
    // not floating-point noise.
    const MIN_COSINE: f64 = 0.9999;
    const MAX_COMPONENT_DIFF: f64 = 2e-3;

    for model in ["complexity", "sensitivity"] {
        let dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("artifacts/models")
            .join(model);
        let embedder = Embedder::load(
            dir.join("config.json"),
            dir.join("model.safetensors"),
            dir.join("tokenizer.json"),
            dir.join("1_Pooling/config.json"),
        )
        .unwrap_or_else(|e| panic!("{model} must load: {e}"));

        let reference = fixture["embeddings"][model].as_array().unwrap();
        let mut worst_cos = 1.0f64;
        let mut worst_text = String::new();

        for (i, text) in texts.iter().enumerate() {
            let want: Vec<f32> = reference[i]
                .as_array().unwrap().iter().map(|v| v.as_f64().unwrap() as f32).collect();
            let got = embedder.embed(text).expect("embed must succeed");

            assert_eq!(
                got.len(), want.len(),
                "{model}: dimension mismatch for \"{text}\""
            );
            let rust_norm: f64 = got.iter().map(|x| f64::from(*x).powi(2)).sum::<f64>().sqrt();
            assert!(
                (rust_norm - 1.0).abs() < 1e-3,
                "{model}: the Rust embedding must be unit-norm (got {rust_norm:.6}); \
                 the ModelCar declares a Normalize module"
            );
            let cos = cosine(&got, &want);
            if cos < worst_cos {
                worst_cos = cos;
                worst_text = text.clone();
            }
            let diff = max_abs_diff(&unit(&got), &unit(&want));
            assert!(
                cos >= MIN_COSINE && diff <= MAX_COMPONENT_DIFF,
                "{model}: Rust and Python embeddings diverge for \"{}\": \
                 cosine {cos:.6} (min {MIN_COSINE}), max component diff {diff:.6} \
                 (max {MAX_COMPONENT_DIFF})",
                &text[..text.len().min(60)]
            );
        }
        println!("{model}: worst cosine {worst_cos:.6} on \"{}\"",
                 &worst_text[..worst_text.len().min(50)]);
    }
}
